// Copyright (C) 2024 owoDra

#pragma once

#include "Logging/LogMacros.h"

PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBE, Log, All);
PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBEExperience, Log, All);
PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBEMovement, Log, All);
PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBEAbilitySystem, Log, All);
PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBEEquipmentSystem, Log, All);
PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBEInventorySystem, Log, All);
PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBEWeaponSystem, Log, All);
PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBETeams, Log, All);
