// Copyright (C) 2024 owoDra

#pragma once

#include "Logging/LogMacros.h"

PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBE_System, Log, All);
PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBE_Loadout, Log, All);
PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBE_HostMigration, Log, All);
PROJECTBE_API DECLARE_LOG_CATEGORY_EXTERN(LogBE_RejoinMatch, Log, All);
