// Copyright (C) 2024 owoDra

#include "ProjectBELogs.h"

DEFINE_LOG_CATEGORY(LogBE);
DEFINE_LOG_CATEGORY(LogBEExperience);
DEFINE_LOG_CATEGORY(LogBEMovement);
DEFINE_LOG_CATEGORY(LogBEAbilitySystem);
DEFINE_LOG_CATEGORY(LogBEEquipmentSystem);
DEFINE_LOG_CATEGORY(LogBEInventorySystem);
DEFINE_LOG_CATEGORY(LogBEWeaponSystem);
DEFINE_LOG_CATEGORY(LogBETeams);
