// Copyright (C) 2024 owoDra

#pragma once

#include "NativeGameplayTags.h"


////////////////////////////////////
// UI.Extension.HUDSlot

PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Extension_HUDSlot_BottomLeft);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Extension_HUDSlot_BottomMiddle);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Extension_HUDSlot_BottomRight);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Extension_HUDSlot_CenterLeft);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Extension_HUDSlot_Center);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Extension_HUDSlot_CenterRight);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Extension_HUDSlot_TopLeft);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Extension_HUDSlot_TopMiddle);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Extension_HUDSlot_TopRight);


////////////////////////////////////
// UI.SettingTable

PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_SettingTable_Control);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_SettingTable_Video);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_SettingTable_Gameplay);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_SettingTable_KeyboardAndMouse);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_SettingTable_GamePad);
PROJECTBE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_SettingTable_Audio);
